In [1]:
!pip install numpy

     ---------------------------------------- 15.8/15.8 MB 2.1 MB/s eta 0:00:00



[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


# Importing the Libraries

In [2]:
import numpy as np

# Creating the numpy matrix

In [5]:
mat1 = np.matrix([[1,2,3], [4,5,6]])

In [6]:
mat2 = np.matrix([[7,8,9], [10,11,12]])

# Addititon operation or matrix

In [7]:
np.add(mat1,mat2)

matrix([[ 8, 10, 12],
        [14, 16, 18]])

# Subtraction operation on matrix

In [11]:
np.subtract(mat2, mat1)

matrix([[6, 6, 6],
        [6, 6, 6]])

# Multiplication operation on matrix

In [12]:
np.multiply(mat1, mat2)

matrix([[ 7, 16, 27],
        [40, 55, 72]])

# Division operation

In [16]:
np.divide(mat2, mat1)

matrix([[7. , 4. , 3. ],
        [2.5, 2.2, 2. ]])

# Power operation

In [19]:
a = np.matrix([[2,3,4], [2,3,4]])
b = np.matrix([[4,3 ,2], [5,4,3]])
np.power(a,b)

matrix([[16, 27, 16],
        [32, 81, 64]])

# Mod Operation

In [21]:
np.mod(mat2, mat1)

matrix([[0, 0, 0],
        [2, 1, 0]])

# Transpose operation

In [22]:
np.transpose(mat1)

matrix([[1, 4],
        [2, 5],
        [3, 6]])

# Reciprocal Operation

In [29]:
np.reciprocal(mat1.astype(float))

matrix([[1.        , 0.5       , 0.33333333],
        [0.25      , 0.2       , 0.16666667]])

In [31]:
mat1.flatten()

matrix([[1, 2, 3, 4, 5, 6]])

In [33]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [38]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [41]:
np.zeros((2,3,4), dtype=np.int32)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [79]:
mat1[0:2, -2:]

matrix([[2, 3],
        [5, 6]])

In [59]:
mat1.

matrix([[1, 2, 3],
        [4, 5, 6]])